const subjects = {
    "topics": [
     "Sports",
     "Animals",
     "Technology",
     "Arts",
     "Music",
     "Literature",
     "Science",
     "Mathematics",
     "History",
     "Geography",
     "Politics",
     "Economics",
     "Religion",
     "Philosophy",
     "Psychology",
     "Sociology",
     "Anthropology",
     "Medicine",
     "Engineering",
     "Education",
     "Environmental Science",
     "Astronomy",
     "Biology",
     "Chemistry",
     "Physics",
     "Agriculture",
     "Law",
     "Business",
     "Marketing",
     "Journalism",
     "Linguistics",
     "Architecture",
     "Culinary Arts",
     "Fashion",
     "Film",
     "Theatre",
     "Dance",
     "Martial Arts",
     "Travel",
     "Hospitality",
     "Fitness",
     "Nutrition",
     "Gaming",
     "Cybersecurity",
     "Robotics",
     "Artificial Intelligence",
     "Data Science",
     "Space Exploration",
     "Veterinary Science",
     "Public Health",
     "Urban Planning",
     "Transportation",
     "Forestry",
     "Oceanography",
     "Meteorology",
     "Pharmacology",
     "Forensic Science",
     "Archaeology",
     "Creative Writing",
     "Mythology",
     "Ethics",
     "Logic",
     "Esthetics",
     "Cognitive Science",
     "Neuroscience",
     "Paleontology",
     "Genetics",
     "Immunology",
     "Toxicology",
     "Materials Science",
     "Energy",
     "Conservation",
     "Human Rights",
     "International Relations",
     "Public Administration",
     "Non-Profit Organizations",
     "Entrepreneurship",
     "Risk Management",
     "Cryptocurrency",
     "Virtual Reality",
     "Augmented Reality",
     "Esports",
     "Crafts",
     "Horticulture",
     "Zoology",
     "Entomology",
     "Ichthyology",
     "Ornithology",
     "Mycology",
     "Volcanology",
     "Seismology",
     "Mineralogy",
     "Gemology",
     "Hydrology",
     "Glaciology",
     "Climatology",
     "Paleoclimatology",
     "Biotechnology",
     "Nanotechnology",
     "Quantum Computing",
     "Sustainable Development",
     "Renewable Energy",
     "Waste Management",
     "Water Resources",
     "Soil Science",
     "Acoustics",
     "Biophysics",
     "Electronics",
     "Optics",
     "Thermodynamics",
     "Astrophysics",
     "Geochemistry",
     "Biogeography",
     "Demography",
     "Remote Sensing",
     "Cartography",
     "Social Work",
     "Community Development",
     "Emergency Management",
     "Tourism",
     "Event Planning",
     "Animation",
     "Graphic Design",
     "Web Design",
     "Industrial Design",
     "Jewelry Design",
     "Interior Design",
     "Product Design",
     "User Experience Design",
     "Advertising",
     "Public Relations",
     "Photography",
     "Videography",
     "Broadcasting",
     "Digital Media",
     "Print Media",
     "Social Media",
     "Telecommunications",
     "Language Studies",
     "Comparative Literature",
     "Poetry",
     "Drama",
     "Non-Fiction Writing",
     "Speech Writing",
     "Copywriting",
     "Technical Writing",
     "Content Creation",
     "Museology",
     "Restoration",
     "Preservation",
     "Archival Science",
     "Library Science",
     "Information Science",
     "Game Design",
     "Game Development",
     "Simulation",
     "Performance Art",
     "Voice Acting",
     "Songwriting",
     "Music Production",
     "Music Theory",
     "Instrumentation",
     "Conducting",
     "Choreography",
     "Costume Design",
     "Set Design",
     "Lighting Design",
     "Sound Design",
     "Makeup Artistry",
     "Special Effects",
     "Puppetry",
     "Magic",
     "Circus Arts",
     "Street Performance",
     "Physical Theater",
     "Improvisational Theater",
     "Stand-up Comedy",
     "Sketch Comedy",
     "Radio",
     "Podcasting",
     "Blogging",
     "Vlogging",
     "Streaming",
     "Influencing",
     "Digital Marketing",
     "Search Engine Optimization",
     "Affiliate Marketing",
     "E-commerce",
     "Retail",
     "Wholesale",
     "Import/Export",
     "Supply Chain Management",
     "Logistics",
     "Procurement",
     "Human Resources",
     "Organizational Behavior",
     "Leadership",
     "Management",
     "Operations Management",
     "Project Management",
     "Quality Assurance",
     "Product Management",
     "Brand Management",
     "Customer Service",
     "Sales",
     "Negotiation",
     "Conflict Resolution",
     "Ethical Hacking",
     "Network Security",
     "Information Security",
     "Cloud Computing",
     "Database Management",
     "Software Engineering",
     "Mobile Application Development",
     "Web Development",
     "Programming",
     "System Administration",
     "IT Support",
     "IT Consulting",
     "Bioinformatics",
     "Computational Biology",
     "Statistical Analysis",
     "Epidemiology",
     "Biostatistics",
     "Health Informatics",
     "Medical Imaging",
     "Radiology",
     "Surgery",
     "Nursing",
     "Dentistry",
     "Pharmacy",
     "Therapy",
     "Psychiatry",
     "Pediatrics",
     "Oncology",
     "Cardiology",
     "Endocrinology",
     "Gastroenterology",
     "Pulmonology",
     "Neurology",
     "Dermatology",
     "Orthopedics",
     "Ophthalmology",
     "Otolaryngology",
     "Urology",
     "Gynecology",
     "Obstetrics",
     "Anesthesiology",
     "Pathology",
     "Radiation Therapy",
     "Nutritional Science",
     "Sports Medicine",
     "Physical Therapy",
     "Occupational Therapy",
     "Speech Therapy",
     "Audiology",
     "Chiropractic",
     "Acupuncture",
     "Naturopathy",
     "Homeopathy",
     "Ayurveda",
     "Traditional Chinese Medicine",
     "Herbal Medicine",
     "Holistic Medicine",
     "Palliative Care",
     "Rehabilitation",
     "Veterinary Medicine",
     "Animal Training",
     "Animal Behavior",
     "Wildlife Conservation",
     "Marine Biology",
     "Fisheries",
     "Aquaculture",
     "Beekeeping",
     "Livestock Management",
     "Pet Care",
     "Zookeeping",
     "Animal Rescue",
     "Wildlife Rehabilitation",
     "Pest Control",
     "Animal Nutrition",
     "Veterinary Surgery",
     "Veterinary Pharmacology",
     "Animal Genetics",
     "Animal Breeding",
     "Animal Welfare",
     "Animal Rights",
     "Environmental Law",
     "Environmental Policy",
     "Environmental Advocacy",
     "Conservation Biology",
     "Ecology",
     "Natural Resource Management",
     "Sustainability",
     "Climate Change",
     "Air Quality",
     "Soil Conservation",
     "Water Conservation",
     "Biodiversity",
     "Ecosystem Services",
     "Environmental Education",
     "Environmental Communication",
     "Green Technology",
     "Clean Technology",
     "Renewable Resources",
     "Sustainable Agriculture",
     "Organic Farming",
     "Permaculture",
     "Urban Agriculture",
     "Hydroponics",
     "Aquaponics",
     "Agroforestry",
     "Food Security",
     "Food Science",
     "Food Technology",
     "Nutrition Education",
     "Dietetics",
     "Food Safety",
     "Culinary Innovation",
     "Food Preservation",
     "Food Processing",
     "Baking",
     "Brewing",
     "Winemaking",
     "Distilling",
     "Food Styling",
     "Food Criticism",
     "Food Photography",
     "Menu Design",
     "Restaurant Management",
     "Catering",
     "Event Catering",
     "Bartending",
     "Mixology",
     "Hospitality Management",
     "Hotel Management",
     "Tourism Management",
     "Travel Planning",
     "Adventure Tourism",
     "Eco-Tourism",
     "Cultural Tourism",
     "Heritage Tourism",
     "Sports Tourism",
     "Wellness Tourism",
     "Hospitality Marketing",
     "Guest Services",
     "Front Office Operations",
     "Housekeeping",
     "Facility Management",
     "Event Management",
     "Convention Planning",
     "Meeting Planning",
     "Exhibition Management",
     "Travel Agency Operations",
     "Tour Guiding",
     "Cruise Ship Operations",
     "Airline Operations",
     "Airport Management",
     "Ground Handling",
     "Aviation Safety",
     "Flight Planning",
     "Pilot Training",
     "Cabin Crew Training",
     "Air Traffic Control",
     "Aerospace Engineering",
     "Aircraft Maintenance",
     "Rail Transport",
     "Road Transport",
     "Maritime Transport",
     "Logistics Engineering",
     "Transport Economics",
     "Transport Policy",
     "Traffic Engineering",
     "Urban Mobility",
     "Smart Transportation",
     "Public Transit Planning",
     "Vehicle Engineering",
     "Automotive Design",
     "Automotive Engineering",
     "Electric Vehicles",
     "Autonomous Vehicles",
     "Vehicle Safety",
     "Motorcycle Mechanics",
     "Bicycle Maintenance",
     "Shipbuilding",
     "Marine Engineering",
     "Port Management",
     "Navigation",
     "Sailing",
     "Boating",
     "Yachting",
     "Scuba Diving",
     "Surfing",
     "Kitesurfing",
     "Windsurfing",
     "Skiing",
     "Snowboarding",
     "Mountaineering",
     "Hiking",
     "Camping",
     "Rock Climbing",
     "Paragliding",
     "Skydiving",
     "Base Jumping",
     "Bungee Jumping",
     "Hang Gliding",
     "Canoeing",
     "Kayaking",
     "Rafting",
     "Rowing",
     "Sailing",
     "Waterskiing",
     "Wakeboarding",
     "Snorkeling",
     "Freediving",
     "Spearfishing",
     "Fishing",
     "Hunting",
     "Archery",
     "Shooting Sports",
     "Martial Arts Training",
     "Boxing",
     "Wrestling",
     "Judo",
     "Karate",
     "Taekwondo",
     "Brazilian Jiu-Jitsu",
     "Muay Thai",
     "Krav Maga",
     "Aikido",
     "Kung Fu",
     "Capoeira",
     "Fencing",
     "Gymnastics",
     "Trampoline",
     "Parkour",
     "Cheerleading",
     "Dance Training",
     "Ballet",
     "Modern Dance",
     "Jazz Dance",
     "Hip Hop Dance",
     "Ballroom Dancing",
     "Latin Dancing",
     "Tap Dancing",
     "Folk Dancing",
     "Square Dancing",
     "Flamenco",
     "Belly Dancing",
     "Pole Dancing",
     "Aerial Silks",
     "Aerial Hoop",
     "Aerial Yoga",
     "AcroYoga",
     "Pilates",
     "Yoga",
     "Meditation",
     "Tai Chi",
     "Qigong",
     "Fitness Training",
     "Personal Training",
     "Strength Training",
     "Cardiovascular Training",
     "CrossFit",
     "Boot Camp",
     "Aerobics",
     "Spinning",
     "Water Aerobics",
     "Zumba",
     "Barre Workout",
     "HIIT",
     "Bodybuilding",
     "Weightlifting",
     "Powerlifting",
     "Sports Coaching",
     "Athletic Training",
     "Sports Nutrition",
     "Sports Psychology",
     "Sports Medicine",
     "Sports Management",
     "Sports Marketing",
     "Sports Journalism",
     "Sports Broadcasting",
     "Sports Analysis",
     "Team Management",
     "Event Planning in Sports",
     "Stadium Management",
     "Sports Officiating",
     "Sports Law",
     "Athlete Representation",
     "Sports Sponsorship",
     "Sports Merchandising",
     "Sports Photography",
     "Sports Videography",
     "eSports Management",
     "eSports Coaching",
     "eSports Analysis",
     "eSports Marketing",
     "eSports Broadcasting",
     "eSports Journalism",
     "Gaming Strategy",
     "Game Testing",
     "Game Marketing",
     "Game Community Management",
     "Game Monetization",
     "Board Games",
     "Card Games",
     "Puzzle Design",
     "Role-Playing Games",
     "Tabletop Games",
     "Live Action Role-Playing",
     "Escape Rooms",
     "Gamification",
     "Interactive Storytelling",
     "Narrative Design",
     "Level Design",
     "Game Art",
     "Game Sound Design",
     "Game Programming",
     "Game Production",
     "Game Quality Assurance",
     "Game Localization",
     "Virtual Game Worlds",
     "Player Experience",
     "User Interface Design",
     "User Interaction Design",
     "Game Analytics",
     "Game Accessibility",
     "Serious Games",
     "Educational Games",
     "Therapeutic Games",
     "Social Impact Games",
     "Mobile Games",
     "PC Games",
     "Console Games",
     "Virtual Reality Games",
     "Augmented Reality Games",
     "Cloud Gaming",
     "Competitive Gaming",
     "Gaming Communities",
     "Gaming Events",
     "Gaming Tournaments",
     "Streaming Culture",
     "Gaming Influencers",
     "Fan Culture",
     "Gaming Merchandising",
     "Game Collectibles",
 ]
 }
 ;  
   
 
  
